#pragma once

#define HANDSHAKE_PACKET_ID 0
#define REQUEST_LOGIN_PACKET_ID 1
#define CREATE_PLATFORM_PACKET_ID 2
#define INITIALIZE_EOS_PACKET_ID 3
#define RESPONSE_LOGIN_PACKET_ID 4
#define REQUEST_ID2STRING_PACKET_ID 5
#define RESPONSE_ID2STRING_PACKET_ID 6