#pragma once

#define HANDSHAKE_PACKET_ID 0
#define CREATE_PLATFORM_PACKET_ID 2
#define INITIALIZE_EOS_PACKET_ID 3
#define BEGIN_SESSION_PACKET_ID 4
#define NOTIFY_MESSAGE_TO_SERVER_PACKET_ID 5
#define RECEIVE_MESSAGE_PACKET_ID 6
#define END_SESSION_PACKET_ID 7
